spring:
  mvc:
    problemdetails:
      enabled: true

  mongodb:
    uri: mongodb://root:zGOLvjdZlWxC_WrlpGVhLQLUMuhNXoUX4dk1rLApnz3GaQ46@66f00834-d382-4893-af20-623ea807a183.asia-southeast1.firestore.goog:443/db-capstone?loadBalanced=true&tls=true&authMechanism=SCRAM-SHA-256&retryWrites=false

server:
  port: 0

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}